### ISSUE TITLE
What would you like help on?

### ISSUE THREAD

**Issue by branflake2267** [tbroyer/gwt-maven-plugin#1]
Could you list a few things that you would like help on or make issues for them?

**Comment by tbroyer** [comment]
The remaining item (`generateAsync`) could be done with an annotation processor and would be better left outside the scope of this project. Closing.

**Comment by lukas0krupa** [comment]
I am considering (and currently testing) migration from legacy plugin. However, I haven't find how to deal with the `generateAsync`.

Any suggestions?

**Comment by tbroyer** [comment]
Don't try to replace it, don't try to automate it.

Add you `Async` interfaces to your `src/main/java` and move on. If/when you change you sync interfaces, GWT compilation will fail, forcing you to update the async ones. And AFAIK, there are tolling in IDEs to help you keep interfaces in sync too (before you even try to compile your project).

Actually (and I said it numerous times over the years), if one interface could be generated from the other, it would be the reverse, inferring the sync methods' return type from the `RequestCallback` type parameter and ignoring the async method's return type, letting you use `void`, `Request` or `RequestBuilder` at your convenience. Of course, it couldn't tell if you'd prefer an `Integer` or an `int`, for example, as a return type; which is why I strongly believe this shouldn't be automated in any way. Assisted in the IDEs, but not automated.
And as I said above, if done anyway, this could (should?) be done with an annotation processor (processing the `@RemoteServiceRelativePath`? possibly adding another annotation for cases where you don't want to use `@RemoteServiceRelativePath`?) and, in any case, better left out of scope of this plugin.

**Comment by lukas0krupa** [comment]
Thanks Thomas, that was very helpful and I agree, it is pointless to have this as a goal.
