### ISSUE TITLE
mvn test not including sources from shared upstream artifact

### ISSUE THREAD

**Issue by avierax** [tbroyer/gwt-maven-plugin#105]
https://travis-ci.org/avierax/ut-config-problem/jobs/324320674#L2013-L2027

The testing phase does work when invoked via `mvn install`

**Comment by avierax** [comment]
The testing phase does work when invoked via `mvn install`

**Comment by tbroyer** [comment]
If you ask me, using any phase earlier than `package` in a reactor build is an anti-pattern.

I'm worried that it might not be that easy to detect whether the project has been packaged or not (if a `gwt-lib`, or its sources packaged if depended on with `<classifier>sources</classifier>`), and behavior has changed at some point between Maven versions.

I'll happily review a pull request, but will very unlikely invest time working on this otherwise. Please use `mvn package` instead (and possibly disable some goals from the `prepare-package` or `package` phases, such as `-Dgwt.skipCompilation`). You could also run the `source:jar-no-fork` at `test` phase instead of `package` (for the shared lib at least), to make it available downstream.
