### ISSUE TITLE
How to generate rpc and i18nMessage classes using your plugin?

### ISSUE THREAD

**Issue by kissenlall** [tbroyer/gwt-maven-plugin#119]

**Comment by ibaca** [comment]
Just use the old plugin to generate I18nMessage, there isn't any downside with this approach. To generate RPC async interfaces you can use the old plugin or https://github.com/intendia-oss/autorpc-gwt, this second option uses APT to generate async interfaces.

**Comment by tbroyer** [comment]
Or you can use the [exec-maven-plugin](https://www.mojohaus.org/exec-maven-plugin/)

Those tools are good for one-shot use, to initialize code, but they're not flexible enough for automated use (IMO): you can't decide whether your RPC async interface methods should return a `Request` or even `RequestBuilder`; you cannot tell which type your I18N constants should be, or the type of your I18N message arguments, or whether your messages should be `String` or `SafeHtml`.

Generating RPC synchronous interfaces from asynchronous ones would be better (but then how about the `@RemoteServiceRelativePath` or `@RpcTokenImplementation` annotations?), and similarly properties files should be generated from interfaces rather than the other way around.

See also #18

**Comment by donatelloOo** [comment]
That should be clearly stated in the documentation !
This is a very common usage.
