### ISSUE TITLE
module autodetection not supported?

### ISSUE THREAD

**Issue by ahoehma** [tbroyer/gwt-maven-plugin#128]
I try to run codeserver without any module defined.
I expected that gwt is finding the module automatically.
With the old org.codehaus.mojo:gwt-maven-plugin this seems to work.
Workaround: I added my one and only module
with 
`<moduleName>com.siemens.spice.goos.widgetset.GoosVaadinWidgetSet</moduleName>`
or
`<modules>com.siemens.spice.goos.widgetset.GoosVaadinWidgetSet</modules>`
If I skip the definition then I got an NPE in 
AbstractDevModePojo line 163
"moduleList.add(configuration.getChild("moduleName").getValue());"

**Comment by tbroyer** [comment]
`moduleName` is used by many goals, so it's required.

 * It's used by `gwt:generate-module` to copy/transform the `src/main/module.gwt.xml` to the appropriately named file (autodetection would be impossible here)
 * It's used by `gwt:compile` to detect stale sources, and whether compilation is needed (or output is already up-to-date).

Not to mention that it breaks as soon as you add, say, a `GoosVaadinWidgetSetDev.gwt.xml`, or start to modularize your GWT modules.

I'm striving for explicitness and implementation simplicity; autodetection would be too fragile and add too much code just so that you don't have to configure one single line in your POM. That's clearly not worth it.

Also, by definition, your `.gwt.xml` are source files that will be processed by Maven plugins, they shouldn't IMO be used as configuration for those plugins as well. Configuration goes into the POM, full stop.

**Comment by ahoehma** [comment]
Ok. Got it :) Thanks for the explanation.
