### ISSUE TITLE
Plugin does not check resource include/exclude when doing conflict-detection with source roots in package-lib

### ISSUE THREAD

**Issue by foal** [tbroyer/gwt-maven-plugin#138]
I have a project that copies license from project root to the META-INF folder by maven-resource-plugin. The configuration is the same as described in this question https://stackoverflow.com/questions/28619630/copy-a-resource-file-with-maven-located-at-the-root-of-the-project.

But it caused the following warning 
```
build	10-May-2020 19:00:16	[INFO] --- gwt-maven-plugin:1.0.0:package-lib (default-package-lib) @ org.jresearch.gwt.time ---
build	10-May-2020 19:00:16	[WARNING] Conflicting path between source folder (/var/atlassian/application-data/bamboo/xml-data/build-dir/GWT-GWTTIM-JOB1/src/main/java/, to be added as resource) and resource (/var/atlassian/application-data/bamboo/xml-data/build-dir/GWT-GWTTIM-JOB1/); skipping.
build	10-May-2020 19:00:16	[WARNING] Conflicting path between source folder (/var/atlassian/application-data/bamboo/xml-data/build-dir/GWT-GWTTIM-JOB1/target/generated-sources/annotations/, to be added as resource) and resource (/var/atlassian/application-data/bamboo/xml-data/build-dir/GWT-GWTTIM-JOB1/); skipping.
build	10-May-2020 19:00:16	[INFO] Building jar: /var/atlassian/application-data/bamboo/xml-data/build-dir/GWT-GWTTIM-JOB1/target/org.jresearch.gwt.time-1.4.8-SNAPSHOT.jar
```
and so no sources in produced JAR.

**Comment by tbroyer** [comment]
This is by design to keep things simple (in the plugin). The goal is to make simple things easy and more complex things possible, so the plugin bails out on any kind of possible conflict and let's you fix it:
 * either move your file to a subfolder that won't contain your sources (or even better, right into `src/main/resources/META-INF/` so you don't even need any kind of configuration)
 * or manually declare your source folders as resources (the plugin will then print `[INFO] …/src/main/java already added as a resource folder; skipping.`)
 * or use `copy-resources` to copy the license file rather than declaring the `project.basedir` as a resource folder.
 * or in this specific case, use the license-maven-plugin's `update-project-license` to automatically keep the `${project.basedir}/LICENSE.txt` file up-to-date and put it into the JAR's `META-INF/`.

That being said, if you think this can easily be implemented, I'll be happy to review a PR.

**Comment by foal** [comment]
Thank you! `copy-resources` and `license:update-project-license` looks reasonable.
