### ISSUE TITLE
Is 2.9.0 ready?

### ISSUE THREAD

**Issue by i0n-** [tbroyer/gwt-maven-plugin#139]
I'm creating a new project but I'm not sure if this plugin support 2.9.0 GWT release ?

**Comment by FrankHossfeld** [comment]
Yes, it does. I am using it with GWT 2.9.0. 

Is there something, that does not work?

**Comment by i0n-** [comment]
Excellent!
Can you help with a basic sample code?
that use <packaging>gwt-app</packaging>

Because I get this:
[ERROR] Unknown packaging: gwt-app @ line 10, column 16

**Comment by TDesjardins** [comment]
@i0n- Could you share your pom? Which version of plugin you are using?

**Comment by FrankHossfeld** [comment]
you can generate a working project here: 

http://www.mvp4g.org/boot-starter-nalu/BootStarterNalu.html

and look inside the client module pom's. That uses gwt-app. And inside the parent pom you can set gwt to 2.9.0.

**Comment by tbroyer** [comment]
Of you look at what changed since 1.0.0, you'll see no code change to support GWT 2.9.0: https://github.com/tbroyer/gwt-maven-plugin/compare/1.0.0...35b0b52

The latest version (2020.5.17) of my gwt-maven-archetypes have also been updated to GWT 2.9.0, among other version bumps (in https://github.com/tbroyer/gwt-maven-archetypes/commit/3fd2a7ab3840dbcd64e8bb45404636f8d58cb953)
