### ISSUE TITLE
Custom Linkers?

### ISSUE THREAD

**Issue by my2iu** [tbroyer/gwt-maven-plugin#143]
Is it possible to use the Maven plugin with a custom GWT code linker? How would I go about doing that?

**Comment by tbroyer** [comment]
The plugin _only_ calls GWT from Maven, so everything you can do with GWT you should be able to do it through this plugin.

Your linker needs to either be in the project itself or in a dependency with scope `compile` (see https://tbroyer.github.io/gwt-maven-plugin/codeserver.html).

The only limitation (that I'm aware of) is that if your linker is a primary linker and doesn't generate a `<moduleShortName>/<moduleShortName>.nocache.js` file, then you won't benefit from the staleness check that avoids recompiling your module when nothing has changed: the module will always be recompiled no matter what (you probably won't be able to run it in dev mode either, because GWT requires the primary linker to be assignable to `CrossSiteIframeLinker`, and is hardcoded for that `.nocache.js` name).

**Comment by my2iu** [comment]
Awesome. I wanted a version of the CrossSiteIframeLinker that would generate cache.js files that could be directly included as scripts in html code as well as being usable in superdevmode. It all worked well.
