### ISSUE TITLE
Change default structure?

### ISSUE THREAD

**Issue by rhuanhianc** [tbroyer/gwt-maven-plugin#157]
I'm working on a conversion to a maven project, but I need the structure of the project to look like this, can I fetch MyModule.xml.gwt and compile, and use devmode with the project like this?

my-project/
|-- src/
|   |-- project/
|   |   |-- client/
|   |   |   |-- MyClass.java
|   |   |   |-- MyModule.gwt.xml
|   |   |   |-- MyModuleGWT.gwt.xml
|   |-- webapp/
|       |-- index.html
|-- target/
|-- pom.xml

**Comment by tbroyer** [comment]
To use `src/` instead of `src/main/java` and `src/main/resources` you should be able to use Maven's own [`sourceDirectory`](https://maven.apache.org/pom.html#directories) and [`resources`](https://maven.apache.org/pom.html#resources).

To use the `.gwt.xml` from the sources, make sure to [configure `<skipModule>true</skipModule>`](https://tbroyer.github.io/gwt-maven-plugin/usage.html) for the `gwt-maven-plugin`.

Now for dev mode, you can try using [the `gwt:devmode` goal](https://tbroyer.github.io/gwt-maven-plugin/codeserver.html#Standalone_applications).

**Comment by rhuanhianc** [comment]
Thank you very much!  In fact it worked perfectly, I can continue my project conversion.  Thanks!
