### ISSUE TITLE
Critical CVEs detected in transitive jar dependencies.

### ISSUE THREAD

**Issue by dneemuth** [tbroyer/gwt-maven-plugin#159]
Hi @tbroyer ,
      currently we are using your plugin to build one of our internal GWT project. thanks for putting so much effort in maintaining this awesome plugin.  we have recently been performing CVE scans to identify high/critical CVEs throughout and amongst, we identified the following jar artifacts which are transitively being pulled by **gwt-maven-plugin**

- maven-surefire-common:jar:**2.22.1** > 3.1.0
- maven-shared-utils:jar:**3.2.0**  > 3.4.2
- maven-core:jar:**3.3.1** > 3.9.2

can i request if it's possible that these versions are bumped up to latest ( which is recommended ) ? Please let me know your thoughts. Thanks.

**Comment by tbroyer** [comment]
* maven-surefire-common has been updated in 8eda8a6c1292ecad984f8b3709fe26f142020759
* maven-shared-utils has been removed by 2a2b801816dfa9573c5d6b83037d2e048d55fe4b
* maven-core has been reliably changed to `provided` in a8232cbb2dd3339b21eafdd1ce6a9c0b9093a37a (see also #160)

So this should be fixed in the next release.
