### ISSUE TITLE
Upgrade to GWT 2.10.0

### ISSUE THREAD

**Issue by jeffrpowell** [tbroyer/gwt-maven-plugin#161]
[https://www.gwtproject.org/release-notes.html#Release_Notes_2_10_0](https://www.gwtproject.org/release-notes.html#Release_Notes_2_10_0)

GWT 2.10.0 released on June 9, 2022. Note the groupId transition, they published 2.10.0 under both org.gwtproject and com.google.gwt. You'll want to solve for folks potentially choosing either (or decide to just support the new org.gwtproject groupId and encourage plugin users to follow suit).

**Comment by tbroyer** [comment]
That's been done last year already (3f742b3) but because it didn't change anything to the plugin (as I relies on the dependencies being declared by the user, without itself having dependencies on GWT artifacts) there's been no need to cut a new release.

Does the documentation need updating though? (I must admit I haven't checked)

**Comment by jeffrpowell** [comment]
Appreciate the clarification; I got tunnel vision just looking at the code of the latest tag, [https://github.com/tbroyer/gwt-maven-plugin/blob/1.0.1/pom.xml#L74](https://github.com/tbroyer/gwt-maven-plugin/blob/1.0.1/pom.xml#L74).

**Comment by tbroyer** [comment]
Site redeployed with updated https://tbroyer.github.io/gwt-maven-plugin/usage.html page
