### ISSUE TITLE
Release versión with GWT 2.11.0 support

### ISSUE THREAD

**Issue by themarioga** [tbroyer/gwt-maven-plugin#164]
Hi.
¿Is there any ETA for the release of the next version with support for GWT 2.11.0, Jakarta and Java 17 on maven?

Thank you for your work on this plugin.

**Comment by tbroyer** [comment]
The plugin is tested against 2.11.0 (https://github.com/tbroyer/gwt-maven-plugin/commit/aba32f1ee145f704ccb1a1a8d6f45d6914b31d25) and with Java 17 and 21 (https://github.com/tbroyer/gwt-maven-plugin/commit/680bc45f1f0948e3e5bd813e2202e121a8cc7bb3), and this hasn't required any change to the code since the 1.1.0 release (https://github.com/tbroyer/gwt-maven-plugin/commits/main/src/main), so no need to cut a new release.

Did you face an issue with gwt-maven-plugin 1.1.0 and GWT 2.11.0 that wasn't caught by the tests?
