### ISSUE TITLE
[Question] Can I hide the devmode gui?

### ISSUE THREAD

**Issue by rhuanhianc** [tbroyer/gwt-maven-plugin#165]
In my GWT project, I use wildfly as a server, and I run GWT with these parameters:
    `<jvmArgs>`
                        <jvmArg>-Xmx4g</jvmArg>
                        <jvmArg>-Xms2g</jvmArg>
                 ` </jvmArgs>`
                  `  <devmodeArgs>`
                        <arg>-codeServerPort</arg>
                        <arg>5360</arg>
                        <arg>-port</arg>
                        <arg>743</arg>
                 `</devmodeArgs>`
A jetty port for wildfly to find and the codeserver port for debugging, so until today I have not been able to use just mvn gwt:codeserver, just the gwt:devmode, but it opens a gui/ui that I don't use, would there be a way to hide this?

**Comment by tbroyer** [comment]
This would be a question for GWT, as this plugin is only there to launch the GWT commands with the appropriate arguments (and allow configuring others in your POM)

I don't get why you need to run Jetty though, which would be the only reason for using devmode rather than codeserver, and it looks like you'd want to solve a symptom rather than tackle the root cause by organizing things differently.

Maybe start by discussing this (your setup and why it is like it is) in the GWT discussion group: https://groups.google.com/g/google-web-toolkit

**Comment by FrankHossfeld** [comment]
As a Windows user, you need to use devmode. Running codeserver and stopping it, will keep one threat alive.
