### ISSUE TITLE
gwt-maven-plugin or gwt-dev seems to compile out @JsExport code in GWT 2.8.0

### ISSUE THREAD

**Issue by Alexwhite3000** [tbroyer/gwt-maven-plugin#23]
Ok, if I run the codeserver now my jsinterop code runs fine. I can open the chrome inspector and instantiate java objects,etc.

However, if I maven build my project for distribution I can't see the @JsExport symbols that I defined for my JS to call.

$ mvn clean compile gwt:compile -Dgwt.logLevel=INFO 
gave me this massive output: http://privatepaste.com/8333ad5a92

I tested with and without <gwt.draftCompile>true</gwt.draftCompile> in my pom.xml. Neither helped. 

By the way I think you were right about the @Jsnamespace being the problem in the other issue. IDK why I didn't think that was it at first.

Any thoughts?

**Comment by tbroyer** [comment]
I'd bet you're not passing `-XjsInteropMode` to `compilerArgs` like you do (did?) with `codeserverArgs`.
Actually, it looks like you try to configure the plugin like it's the `org.codehaus.mojo:gwt-maven-plugin`. Please use the `gwt:help` goal to learn about how to configure this plugin (e.g. `mvn gwt:help` to list goals, and `mvn gwt:help -Dgoal=compiler -Ddetail=true` to get help on a specific goal, `gwt:compile` in this example).
Closing this issue as it looks like a misconfiguration on your part. Will reopen if needed.

> $ mvn clean compile gwt:compile -Dgwt.logLevel=INFO

Why on earth are you calling the `gwt:compile` goal explicitly rather than using lifecycle phases? (`prepare-package` or `package`) If you want to skip tests, ask Maven to skip them (`-DskipTests`, or even `-Dmaven.test.skip` to skip compiling them).

> I tested with and without true in my pom.xml. Neither helped.

Which `true` are you talking about?

**Comment by Alexwhite3000** [comment]
> Which true are you talking about?
Oops, a minor markdown error. I was trying with gwt.draftCompile to both true and false.

> I'd bet you're not passing -XjsInteropMode to compilerArgs like you do (did?) with codeserverArgs
I'm working with two projects, the one generated by your archetype and a legacy gwt project that I'm trying to convert to use gwt-2.8 w/jsinterop. I was able to get the archetype-based one working by putting compilerArgs in the root pom,client, and shared. It was already in the root (and I think the client) but definitely not shared. The other proj is a bit of a frankenstein, I'll keep at it. Thanks alot for your help.
