### ISSUE TITLE
Test source dependencies not configured correctly in some cases

### ISSUE THREAD

**Issue by ibaca** [tbroyer/gwt-maven-plugin#38]
This is the situation, if you have a project like e2e [reproduced here](https://github.com/ibaca/tbroyer.gwt-maven-plugin/tree/test-classpath), and you add a GwtTest in the shared-gwt module, the e2e-shared and e2e-module dependencies are only configured corretly in some cases:

* `project> mvn -am -pl :e2e-shared-gwt test` **fail** with "No source code is available..."
* `project> mvn -am -pl :e2e-shared-gwt install`**success**
* `project/e2e-shared-gwt> mvn test` **success** (need other artifact to be in the local repo)

For the failure case, the problem is that only the `<project>/target/classes` is added to the classpath (which not contains source files), but I'm not sure if this is a maven, gwt-maven-plugin or just that I'm not configuring the project correctly. Thanks.

**Comment by tbroyer** [comment]
This is because the maven-source-plugin is bound to the prepare-package (or even package) phase, which comes after the test phase. As you need sources for GWT tests, then either run source:jar earlier, or always run at least up until the prepare-package or package phase.

This is purely a Maven "issue" from my PoV, due to its linear lifecycle and how it's applied to reactor builds. I personally consider the only 2 phases you should use as goals when calling a multi-module build are package and verify. (install and deploy have specific uses --namely share the built artifacts with other projects, or working around ill-designed plugins or Maven lifecycle-- so does clean, obviously)

**Comment by ibaca** [comment]
Thanks! Using the package goal is ok. 

Just one thing. Looks like you admit that the test goal is broken at the test phase (maven problem), why don't you set the default phase of the TestMojo to PREPARE_PACKAGE (or PACKAGE) so is clear that the plugin requires at least this phase to work properly. Or one step further, use INTEGRATION_TEST which solve the problem and is still meaningful.

**Comment by tbroyer** [comment]
Because the test phase is when it's appropriate to run tests, and it works OK on one module. The problem arises in multi-module builds when you have dependencies on non-gwt modules where the maven-source-plugin is used. The proper fix (if you want it) is to run source:jar earlier, **or** just always use package at a minimum in multi-module builds.
