### ISSUE TITLE
SourceMaps and production builds

### ISSUE THREAD

**Issue by timeu** [tbroyer/gwt-maven-plugin#53]
Might not be an issue of the `gwt-maven-plugin` but I am somehow stuck with this. 
I want to add support for sourceMaps in production builds and I am not sure what the best way is and also ran into some issues. 

I basically have a maven project based on the [modular-requestfactory](https://github.com/tbroyer/gwt-maven-archetypes) archetype. 
To generate the the sourcemaps I added this to the -client module:

```XML
<build>
  <plugins>
     <plugin>
        <groupId>net.ltgt.gwt.maven</groupId>
          <artifactId>gwt-maven-plugin</artifactId>
           <configuration>
             <moduleName>${gwt.module}</moduleName>
             <moduleShortName>browser</moduleShortName>
              <compilerArgs>
                 <param>-saveSource</param>
                 <param>-saveSourceOutput</param>
                 <param>${project.build.directory}/extra</param>
               </compilerArgs>
             </configuration>
         </plugin>
   </plugins>
</build>
```

However I run into an error when the GWT compiler tries to save the source files:

```
 [ERROR] Fatal error emitting artifact: src/gen/com/gmi/nordborglab/browser/shared/proxy/CandidateGeneListEnrichmentPageProxyAutoBean_com_google_web_bindery_requestfactory_shared_impl_EntityProxyCategory_com_google_web_bindery_requestfactory_shared_impl_ValueProxyCategory_com_google_web_bindery_requestfactory_shared_impl_BaseProxyCategory.java
[INFO] java.io.FileNotFoundException: /home/GMI/uemit.seren/mnt/user/uemit.seren/Code/GWAPortal/genophenbrowser/genophenbrowser-client/target/extra/browser/src/gen/com/gmi/nordborglab/browser/shared/proxy/CandidateGeneListEnrichmentPageProxyAutoBean_com_google_web_bindery_requestfactory_shared_impl_EntityProxyCategory_com_google_web_bindery_requestfactory_shared_impl_ValueProxyCategory_com_google_web_bindery_requestfactory_shared_impl_BaseProxyCategory.java (File name too long)
```
I thought that the issue was [solved in 2.4](https://github.com/gwtproject/gwt/issues/6014). 

In general I am wondering what the best practice is to package the the sourcemaps ? I was thinking of doing this in the `-client` module so that the generated client `gwt-app` has those assets already packaged. 

Alternatively I could modify the `-server` module and copy the resources from the `-client/target/` folder when I package the server `war` artefact, similar to how it is done in the official gwtprojects.org page: 
https://gwt.googlesource.com/gwt-site-webapp/+/master/pom.xml#144

**Comment by tbroyer** [comment]
* you could point `-saveSourceOutput` to your `${project.build.directory}/${project.finalName}` (or whatever value you configured for `webappDirectory`) or a subdirectory to have it packaged into your `gwt-app` artifact (you could also use `resources:copy-resources` during the `prepare-package` phase if you liked); or you could point `-saveSourceOutput` to some path ending in `.war` or `.zip` (`.jar` also works) to get sources to a single archive and then use `build-helper-maven-plugin` to attach it as a secondary artifact that you could then integrate into your final WAR as an overlay.
 * gwtproject/gwt#6014 was a different issue (or actually, the same underlying issue, but at a different place, so fixed only there – well, `-saveSource` didn't actually exist at the time, so let's say "reintroduced at a different place"). Please open an issue over GWT. BTW, I don't think it'd happen if your output is a WAR/ZIP/JAR rather than a directory.

Anyway, closing as this is not directly related to the plugin.

**Comment by timeu** [comment]
Ok great thanks for listing the options. 
Originally I tried to output it to `${project.build.directory}/${project.finalName}` but ran into the "file to long" issue. 
I will try the `.war` option and create an issue over at GWT.
