### ISSUE TITLE
Recompiling gwt on server source change

### ISSUE THREAD

**Issue by zufarfakhurtdinov** [tbroyer/gwt-maven-plugin#54]
I've created a sample:
https://github.com/zufarfakhurtdinov/gwtpluginsample
There is a single module contains server(simple httpServlet named MyServlet) and client code.
.gwt.xml just contains **source path="client"**
When I change MyServlet code and do mvn package, gwt is recompile each time in spite of no client code changes.
Mojo gwt-maven-plugin (commented in sample) process it correctly.

**Comment by tbroyer** [comment]
Mojo's Maven Plugin for GWT will parse your `*.gwt.xml` file(s?) to filter out non-client sources, but this is brittle and will, for example, fail to detect changes to non-client code that would nevertheless change the compilation output (e.g. constants, annotations, or GWT generators or linkers).

This plugin, on the other hand, is built on the assumption that you'll organize your project separating client and server code in distinct Maven modules, so such filtering is much less useful.

So what you're experiencing is actually the expected behavior.
