### ISSUE TITLE
Source files in the target folder

### ISSUE THREAD

**Issue by natros** [tbroyer/gwt-maven-plugin#55]
Hi, 

Sometimes after some refactoring the gwt compiler complains about some missing references. In this case what I do is to delete all java source files within the target folder. As far as I can tell, these java source files are copied during the import sources (gwt-maven-plugin:1.0-rc-6:import-sources). Is there any need to have the source code in the target folder since the same code exists in the src folder and is more up to date?

I'm using IntelliJ and when I change the name of a class, the IDE renames the java files in the src folder and renames the .class file in the target directory, but does not change the name of the .java file inside the target folder thus leaving these java files forever or until I delete them.

I understand that these files may be necessary for the gwt-lib, but I'm not so sure if they are needed for gwt-app

I'm using java 8, OSX, IntelliJ, last gwt 2.8 snapshot, and gwt:devmode

Thank you.

**Comment by natros** [comment]
Hello, 

After moving (IDE refactoring) the file certidao/CertidaoEstagioPanel.java to certificado/CertificadoEstagioPanel.java I'm getting
```
[INFO]    Job pt.ipb.suplemento.Suplemento_1_0
[INFO]       starting job: pt.ipb.suplemento.Suplemento_1_0
[INFO]       Compiling module pt.ipb.suplemento.Suplemento
[INFO]          Tracing compile failure path for type 'pt.ipb.suplemento.client.modulos.sup.certidao.CertidaoEstagioPanel'
[INFO]             [ERROR] Errors in 'file:/Users/fsousa/Projects/ipb/suplemento/suplemento-client/target/classes/pt/ipb/suplemento/client/modulos/sup/certidao/CertidaoEstagioPanel.java'
[INFO]                [ERROR] Line 10: The import pt.ipb.suplemento.shared.model.Item.CERTIDAO_ESTAGIO cannot be resolved
[INFO]                [ERROR] Line 59: CERTIDAO_ESTAGIO cannot be resolved to a variable
[INFO]          [ERROR] Aborting compile due to errors in some input files
```

I have to manually remove the source files from target
```
find target/classes -type f -name CertidaoEstagioPanel\*
target/classes/pt/ipb/suplemento/client/modulos/sup/certidao/CertidaoEstagioPanel.java
target/classes/pt/ipb/suplemento/client/modulos/sup/certidao/CertidaoEstagioPanel.ui.xml
```

**Comment by natros** [comment]
ping

**Comment by dmg46664** [comment]
@natros - Looks like `gwt-maven-plugin`[delegates](https://github.com/tbroyer/gwt-maven-plugin/blob/409ec6c53bcf72c35476e3a10699ec5ea283791a/src/main/java/net/ltgt/gwt/maven/AbstractImportSourcesMojo.java) to [`MavenResourceExecution`](https://github.com/finalist/Maven-Filtering/blob/master/src/main/java/org/apache/maven/shared/filtering/MavenResourcesExecution.java). 

I believe you're therefore asking for a feature request on that project to better synchronise resources, unless you can recommend a better alternative?

I don't have a good handle on why the `target` directory exists but it appears canonical. Likely it's necessary to support annotation processing or some such code and/or resource processing use case.

**Comment by tbroyer** [comment]
FWIW, I'm still wondering what to do with those `import-sources` goals, and whether I should make a `gwt:jar` for libraries instead of marking source directories as resource directories too. This however means I would also need to change `gwt:compile` and `gwt:test` goals to use the source directories too.

BTW, the reason it's done this way today is:
 * because that's (probably) how you'd do it if the plugin didn't do it for you (i.e. declare `src/main`java` as a resources directory, and use the `exec-maven-plugin` to run the GWT tools)
 * because if you'd do it that way, you possibly would want to make use of resource filtering (and the plugin currently ignores source directories that have been declared as resources directories, to explicitly permit those cases); though I believe one should not work this way (you should rather use the [`template-maven-plugin`](http://www.mojohaus.org/templating-maven-plugin/)

So, I might very well move towards a `gwt:jar` goal, and `gwt:compile` and `gwt:test` adding the compile source roots to the classpath; and this is BTW the main reason this plugin isn't at 1.0 yet.

Closing now as I don't think there's anything actionable in this issue thread (and blame Maven –and possibly IntelliJ here– for broken incremental builds).

**Comment by tbroyer** [comment]
OK, so, `gwt:package-lib` (rather than `gwt:jar`) is finally here in 7c4e86afa0e8785805882a60e19d59be4b56f23b
