### ISSUE TITLE
mvn test in gwt-lib packaging does not run test cases

### ISSUE THREAD

**Issue by dnouls** [tbroyer/gwt-maven-plugin#56]
I have created a maven project using this the gwt-maven plugin (package type is gwt-lib)

I have written regular unit tests in the src/test/java folder and there also some GWTTestCases.
When I use the mvn install operation, which also triggers tests (normally) I don't see my unit tests running. Not even the pure JUnit tests.

What am I missing ? 

PS: Sorry for creating an issue for this, but I see no other channel to ask questions about this plugin.

**Comment by tbroyer** [comment]
Actually, `gwt:test` defaults to running test suites, rather than test cases (see https://tbroyer.github.io/gwt-maven-plugin/test-mojo.html#includes). Given the perf gains, I set it as the default to _enforce_ (or at least incentivize to) the “best practice”.

NB: I should settle on a channel for such questions; the issue tracker is OK for now, as well as StackOverflow (I monitor the `gwt` tag) or the GWT forums on Google Group.

**Comment by dnouls** [comment]
Thanks, that did it

**Comment by rjeeb** [comment]
@tbroyer is this applied on Junit 5 too?

**Comment by tbroyer** [comment]
GWT only supports JUnit 3 kind of tests (JUnit 4 to some extent, though actually only for the `@RunWith(Suite.class)`).

Please note that if you have a shared library (both client/GWT and JVM), you shouldn't use a `gwt-lib`; you should have a `jar` for the server and a `gwt-lib` that works as an _adapter_: see https://tbroyer.github.io/gwt-maven-plugin/
(if you find that verbose, remember that you're using Maven)
