### ISSUE TITLE
Changing style with gwt:devmode is not working

### ISSUE THREAD

**Issue by natros** [tbroyer/gwt-maven-plugin#61]
Setting the style to PRETTY

```xml
      <plugin>
        <groupId>net.ltgt.gwt.maven</groupId>
        <artifactId>gwt-maven-plugin</artifactId>
        <version>1.0-rc-6</version>
        <extensions>true</extensions>
        <configuration>
          <sourceLevel>1.8</sourceLevel>
          <moduleName>pt.ipb.candidaturas.sa.ServicosAcademicos</moduleName>
          <moduleShortName>sa</moduleShortName>
          <moduleTemplate>${project.basedir}/src/main/${gwt-moduleTemplate}</moduleTemplate>
          <style>PRETTY</style>
          <startupUrls>
            <startupUrl>sa/index.html</startupUrl>
          </startupUrls>
        </configuration>
      </plugin>
```

is always -style, OBFUSCATED

![gwt_development_mode](https://cloud.githubusercontent.com/assets/4996289/18786574/849daf2e-8196-11e6-9725-75cd67d8e230.png)

Thank you

**Comment by tbroyer** [comment]
That argument is new in 2.8, so you have to pass it through `<devmodeArgs>` (and similarly for `<codeserverArgs>`).

```xml
<devmodeArgs>
  <arg>-style</arg><arg>PRETTY</arg>
</devmodeArgs>
```

Because this plugin aims at working with the last 2 versions of GWT (at a minimum, and that currently includes 2.7 and 2.6), and because I don't want to include any kind of version-checks; I won't consider this a bug.

BTW, you won't find `style` (nor `failOnError` fwiw) as a parameter in http://tbroyer.github.io/gwt-maven-plugin/devmode-mojo.html (of `mvn gwt:help -Dgoal=devmode -Ddetail`)

**Comment by natros** [comment]
I was fooled by the IDE that suggests the `<style>` option that points to plugin.xml

```xml
<parameter>
          <name>style</name>
          <type>net.ltgt.gwt.maven.GwtOptions$Style</type>
          <required>false</required>
          <editable>true</editable>
          <description>Script output style: OBFUSCATED, PRETTY, or DETAILED.</description>
        </parameter>
```

You are right, the devmode goal and the documentation does not reference this parameter.
