### ISSUE TITLE
How to reduce class-path length for GWT compile when using Request Factory

### ISSUE THREAD

**Issue by dfht** [tbroyer/gwt-maven-plugin#73]
Sorry to open another issue, but my last one was closed before I'd really ended what I wanted to ask.....
I read a lot how this plug-in is better at facilitating or encouraging client/server split to enable smaller GWT compile class-paths and other benefits like not packaging unnecessary client code into the server  or server code in the source jars etc. There's seems to be a kind of consensus attitude that if your path is too long then it's your own fault for not having the correct factoring and dependencies. 
I have many projects and they are carefully split into client- and server ones.
I use Request Factory and the editor framework. 
However, my screens refer to the request factory interfaces for their data. 
This means that the projects with screens must have the projects containing the RF interfaces as dependencies.
The request factory interfaces then refer to back-end entity code in their @ProxyFor annotations. That being so, the projects with RF interfaces must have back-end entity code in their preferences. That all being so, it seems to mean that my GWT projects with screens simply must drag in all of the back-end entity projects (and all of the third party jars they depend on - spring hibernate etc. etc.) as transitive dependencies. So I am wondering what exactly I should do (or can I do) to reduce the GWT compilation class-path?

**Comment by tbroyer** [comment]
This is not really related to this plugin (it'd be the same whichever the build system or plugin, though possibly with different sets of solutions for each). Also, if you don't mind, I'd rather keep this issue tracker mainly for bug reports and enhancement requests, and use the [GWT forum](https://groups.google.com/forum/#!forum/google-web-toolkit) for discussions, and Stackoverflow for Q&A.  
That said, thank you for reaching for more information about this plugin; I value that and hope I can improve it in response to such feedback (while keeping it as simple as possible)

Back to your issue:

At the GWT level, you can use `@ProxyForName` instead of `@ProxyName` to cut (or even invert!) your dependencies (this is what I use in the [modular-requestfactory archetype](https://github.com/tbroyer/gwt-maven-archetypes).

At the Maven level, you could use exclusions to limit the transitive dependencies brought by your dependency to your backend entity code. Actually, GWT doesn't even need the classes referenced by your `@ProxyFor` annotations (only the annotation processor checking the interfaces and generating the `DeobfuscatorBuilder` needs them), so you might even depend on your request factory interfaces and exclude all other dependencies (**including** the back-entity projects).

At the project architectural level, you could make it so that your backend entity code does not have dependencies (or "hide" them behind interfaces, implemented elsewhere) so you don't bring too much things transitively; using an architecture inspired by the [Clean Architecture](https://8thlight.com/blog/uncle-bob/2012/08/13/the-clean-architecture.html), or the [Hexagonal Architecture](http://alistair.cockburn.us/Hexagonal+architecture) (aka Ports & Adapters)

Other alternatives include:
 * have the request factory interfaces project assemble an addition artifact including only what's needed for GWT client (using the maven-assembly-plugin or the [maven-jar-plugin](https://maven.apache.org/plugins/maven-jar-plugin/examples/attached-jar.html)), and use that from the GWT client project, so it won't bring transitive dependencies
 * use the [maven-dependency-plugin](https://maven.apache.org/plugins/maven-dependency-plugin/unpack-mojo.html) to unpack needed dependencies into a single folder and use that as a single dependency (with `<scope>system</scope>`), such that all your dependencies are reduced to a single classpath entry.

---
BTW, it's not because an issue is closed that you cannot continue to comment and have a discussion on it ;-)

**Comment by dfht** [comment]
Wow, you are quick :). I guess I should put it on forums instead. Sorry about that... I tend to not ask somany questions as I normally like to figure stuff out for myself, but I've found your answers and insights most useful several times now.
And thanks again for your excellent answer. I think it gives me everything I need here.
Between exclusions and @ProxyForName it should certainly be possible to rationalize the path now.
Exclusions hadn't occurred to me (don't know why!), but I actually anticipated you might mention the @ProxyForName, but  didn't want to prejudice your answer :). Would the static validation against method names on entities still occur (and if so how would the annotation processor/validator find them if they're not on the class-path)? I actually don't mind (prefer even!) if they don't occur, as almost all of my RF proxies are generated from models, so static validation is mostly unnecessary and kind of an extra overhead (for the same reason I tend to avoid having Eclipse GWT plug-in natures and builders on my projects). 

I hadn't spotted the archetype as I don't use archetypes to create projects (I find the whole Jet thing when making your own very tiresome, so I generate projects in different ways based on models and using Groovy scripts etc.) so that's probably why  didn't spot the modular request factory archetype.........

Anyway, thanks for your quick (and comprehensive) response, and sorry again for posting it as an issue!

**Comment by tbroyer** [comment]
> Wow, you are quick :)

Ha, that was pure chance ;-)

> Would the static validation against method names on entities still occur (and if so how would the annotation processor/validator find them if they're not on the class-path)?

The annotation processor does more than performing static validation; it also generates a `DeobfuscatorBuilder` that's needed at runtime (server-side). So, the annotation processor **needs** the classes the be in the classpath, and this is why the modular-requestfactory archetype runs it (through the `ValidationTool` command-line tool, which is just a wrapper actually) [explicitly in the *-server module](https://github.com/tbroyer/gwt-maven-archetypes/blob/983261380c0a5091d1001032ca5602f15d59d421/modular-requestfactory/src/test/resources/projects/basic-rf/reference/basic-rf-server/pom.xml#L41-L65) (technically, you could also just [invoke JavaC with the appropriate arguments](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javac.html): `-d` and the name of the class to process in place of –or in addition to– source files, but Maven makes it hard, as usual).

But the generator that runs during the GWT compilation (client-side code), does not need the backend classes to be in the classpath.

> Anyway, thanks for your quick (and comprehensive) response, and sorry again for posting it as an issue!

No problem.

**Comment by dfht** [comment]
Hi Thomas,
Thanks again for your pointers. Fortunately, my back-end code is very clean, and I use interfaces for the proxied classes (I have a service layer decorator to help wire up at run-time etc.) . That being so, much better separation was possible just by splitting the interfaces into a separate project, thus avoiding all other back-end dependencies on the GWT compilation path (using a project/module with your gwt-app packaging to do the GWT compile and bringing client and server sides together at the 'bottom' via a war project that overlays the gwt-app etc.).

Now I just have a few more questions. It seems to me that all of my GWT projects (client-only or shared) can be nicely packaged with your gwt-lib packaging, and  I've verified that this works for me. However, I also see that just using maven-sources and building a separate sources jar works fine too, and it's nice in a way to separate the source and potentially avoid building it into the final war file (avoiding distributing our IP etc.). **If I use maven-sources, will the GWT compilation goal still include the straight classes jar on it's class-path as well as the sources jar, or does it just use the sources jar?** I ask because if it puts both on the path, then it seems that I'd be better using the combined jars produced by your gwt-lib packaging, as we develop on windows, with  very many projects/modules, and it's  important to keep the class-path length down. So my ideal would be separate source jars, but not at the expense of making the GWT compile path too long! If the compile does bring in the non-sources jars, is there any chance of making it not include them in cases where a project depends on both the normal and sources jar (I can't see why you'd want the normal jar on the path in these cases)?

**Comment by tbroyer** [comment]
The GWT classpath will contain both JARs (because the classes jar might also contain required resources, generators and/or linkers, and annotations –that need to be in compiled form to be usable by generators–)

If you really want/need to cut down your classpath length; I'd first suggest using the "unpack everything in a single directory" hack I described above, or building an intermediate module that would bundle everything into a single JAR for use by the GWT module.  
Alternatively, you might just want to run the build in a Linux box running in Docker ;-)  
Other option: remove dependencies on non-sources jars and disable the maven-compile-plugin; that won't work if you have tests though (they need to be compiled by JavaC, so they need the classes jar dependencies), but note that that could be done in 2 modules: one with classes with `provided` scope or marked as optional along with sources jar, that doesn't call GWT, and another that depends on the first and calls GWT (possibly re-adding select classes-jar dependencies with `test` scope).

Of course, packing the sources inside every jar is an option, if you're OK deploying your sources down to production servers.
