### ISSUE TITLE
Aggressive org.eclipse.jetty.util logging with gwt:codeserver

### ISSUE THREAD

**Issue by shauntarves** [tbroyer/gwt-maven-plugin#74]
When I run mvn gwt:codeserver, Jetty logs to my terminal at DEBUG level. When I was previously using the mojo GWT maven plugin, I was able to solve this by passing in a jvm argument to the CodeServer execution specifying a logback.configurationFile per https://github.com/gwt-maven-plugin/gwt-maven-plugin/issues/147

Trying to replicate that same workaround with this plugin isn't yielding any success. I've tried both
`<jvmArgs>-Dlogback.configurationFile=logback_superdevmode.xml</jvmArgs>` and `<systemProperties><logback.configurationFile>logback_superdevmode.xml</logback.configurationFile></systemProperties>` in my pom.xml file. When I run with -X full debug logging, I see those parameters making it to the call, but the logging behavior isn't changing.

```
[DEBUG] Arguments: -Dlogback.configurationFile=logback_superdevmode.xml com.google.gwt.dev.codeserver.CodeServer -logLevel DEBUG -workDir [...]
```

Terminal example: 

```
[INFO] --- gwt-maven-plugin:1.0-rc-6:codeserver (default-cli) @ cons3rt-venue ---
[INFO] Turning off precompile in incremental mode.
[INFO] Super Dev Mode starting up
[INFO]    workDir: xxxxxxxx/target/gwt/codeserver
[INFO] 17:14:11.159 [main] DEBUG org.eclipse.jetty.util.log - Logging to Logger[org.eclipse.jetty.util.log] via org.eclipse.jetty.util.log.Slf4jLog
[INFO] 17:14:11.168 [main] INFO org.eclipse.jetty.util.log - Logging initialized @2071ms
[INFO]    Loading Java files in com.xxxxx.
[INFO]    Module setup completed in 3779 ms
[INFO] 17:14:16.848 [main] DEBUG org.eclipse.jetty.util.component.ContainerLifeCycle - org.eclipse.jetty.server.Server@7fa3771d added {qtp765206903{STOPPED,8<=0<=200,i=0,q=0},AUTO}
[INFO] 17:14:16.857 [main] DEBUG org.eclipse.jetty.util.component.ContainerLifeCycle - HttpConnectionFactory@239df0d8{HTTP/1.1} added {HttpConfiguration@5e73dc09{32768/8192,8192/8192,https://:0,[]},POJO}
[INFO] 17:14:16.859 [main] DEBUG org.eclipse.jetty.util.component.ContainerLifeCycle - ServerConnector@27a0ac49{null}{0.0.0.0:0} added {org.eclipse.jetty.server.Server@7fa3771d,UNMANAGED}
[...]
```

**Comment by tbroyer** [comment]
Check (and tweak if needed) the classpath for the CodeServer (first, check why you have a logback dependency there; you seem to have a properly modularized project so there's no reason to have logback in your client code). Beside dependency exclusion, you can play with the dependencies scope and `gwt:codeserver`'s `classpathScope` to refine the classpath.

Then, you have all the information in the `mvn -X` to run the process manually and tweak further until you find a proper configuration, and then replicate it in your POM.

In this case, I suspect the issue is that your `logback_superdevmode.xml` path is wrong, and Logback does not seem to complain (or even log anything) when it can't find it: https://github.com/qos-ch/logback/blob/ad2081473e6bc5f495a2a8b0eca81c72c890b68a/logback-classic/src/main/java/ch/qos/logback/classic/util/ContextInitializer.java#L88-L115

But I'm afraid this doesn't look like a bug in this plugin, as your system property has correctly been passed to the forked JVM (at least that's what the logs say, and I have good confidence that it's accurate: https://github.com/tbroyer/gwt-maven-plugin/blob/1.0-rc-6/src/main/java/net/ltgt/gwt/maven/AbstractDevModeMojo.java#L228-L231)

**Comment by tbenbrahim** [comment]
This fixed it for me, for anyone who comes across the same issue:
`-Dorg.eclipse.jetty.LEVEL=INFO -Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog` as part of `extraJvMArgs`
