### ISSUE TITLE
"mvn tomcat7:run" returns 404 for Javascript files

### ISSUE THREAD

**Issue by foxylion** [tbroyer/gwt-maven-plugin#78]
I'm using the sample project of the maven archetype. When running the following commands:
```
console1$ mvn gwt:codeserver
console2$ mvn tomcat7:run
```

I get a 404 for `http://127.0.0.1:8080/app/app.nocache.js` when opening `http://127.0.0.1:8080/`.

GWT codeserver is generating the javascript files in `target/gwt/launcherDir/` but it looks like Tomcat is not picking up those files. Do you have any idea why that does not work?

**Comment by tbroyer** [comment]
This is unrelated to the gwt-maven-plugin actually (as it's a tomcat7-maven-plugin configuration issue).

With the tbroyer/gwt-maven-archetypes, you need to run `tomcat7:run` with the `env-dev` profile (which can be enabled with the `env` property set to `dev`: `-Denv=dev`); otherwise it runs your app in prod mode.

**Comment by foxylion** [comment]
Thanks, didn't know that.
