### ISSUE TITLE
web resources not copied into WAR

### ISSUE THREAD

**Issue by taxone** [tbroyer/gwt-maven-plugin#85]
Hi,
I'm using the latest version of the plugin (1.0-rc-7).
In the pom.xml, the packaging is set to **gwt-app**.
After calling the maven goals "_package_" and "_gwt:devmode_", the resources stored in "**/src/main/webapp**" are not copied into the WAR. It seems that such resources are not processed at all. Is it a bug? If it's not a bug, how should static resources (html, css) and the web.xml be managed?
Thanks

**Comment by tbroyer** [comment]
This is by design.

See how `src/main/webapp` is not mentioned in https://tbroyer.github.io/gwt-maven-plugin/usage.html#Project_layout
See also https://github.com/tbroyer/gwt-maven-plugin/issues/2#issuecomment-19609616 which discussed that issue (but thanks for filing this issue, as that comment was hard to find back).

 * you can put your static resources in the GWT module's [public path](http://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html#DevGuideModules) (`<public path="…"/>`, which by default is a subpackage named `public`); or you could use the `maven-resources-plugin`'s `copy-resources` in the `prepare-package` phase to copy (and possibly filter) `src/main/webapp` to `${project.build.directory}/${project.build.finalName}`
 * you probably shouldn't have a `web.xml` file in there though (wouldn't work in the _public path_ btw); either use the `war` packaging (and explicitly configure the plugin to execute the `compile` goal, possibly also `enforce-encoding`, `generate-module`, `add-super-sources`, and/or `test`) and then live with client and server classes mixed (which I'd discourage and is one of the reasons this plugin was created in the first place), or create another `war` module that uses the `gwt-app` as an [overlay](https://maven.apache.org/plugins/maven-war-plugin/overlays.html) (which is the recommended usage; see my [gwt-maven-archetypes](https://github.com/tbroyer/gwt-maven-archetypes), or the [`e2e` integration test](https://github.com/tbroyer/gwt-maven-plugin/tree/1.0-rc-7/src/it/e2e) for examples of that setup).
