### ISSUE TITLE
gwt:devmode no longer adds runtime-scoped dependencies to classpath (regression from rc7 to rc8)

### ISSUE THREAD

**Issue by ge0ffrey** [tbroyer/gwt-maven-plugin#91]
In rc7, we can run `gwt:devmode` with this configuration:
```
            <devmodeArgs>
              <!-- GWT Super Dev Mode: Replace default backend by WildFly -->
              <arg>-server</arg>
              <arg>org.jboss.errai.cdi.server.gwt.EmbeddedWildFlyLauncher</arg>
              ...
            </devmodeArgs>
```

In rc8, we get this exception.
```
[INFO] --- gwt-maven-plugin:1.0-rc-8:devmode (default-cli) @ optashift-employee-rostering ---
[INFO] Ignoring org.optaplanner.openshift:optashift-employee-rostering-shared:jar:0.1.0-SNAPSHOT; neither a gwt-lib or jar:sources; Did you forget to use <type>gwt-lib</type> in the dependency declaration?
[WARNING] Unable to load server class 'org.jboss.errai.cdi.server.gwt.EmbeddedWildFlyLauncher'
[WARNING] java.lang.ClassNotFoundException: org.jboss.errai.cdi.server.gwt.EmbeddedWildFlyLauncher
[WARNING]       at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[WARNING]       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[WARNING]       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[WARNING]       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[WARNING]       at java.lang.Class.forName0(Native Method)
[WARNING]       at java.lang.Class.forName(Class.java:348)
[WARNING]       at com.google.gwt.dev.DevMode$ArgHandlerServer.setString(DevMode.java:181)
[WARNING]       at com.google.gwt.util.tools.ArgHandlerString.handle(ArgHandlerString.java:26)
[WARNING]       at com.google.gwt.util.tools.ToolBase.processArgs(ToolBase.java:240)
[WARNING]       at com.google.gwt.dev.ArgProcessorBase.processArgs(ArgProcessorBase.java:30)
[WARNING]       at com.google.gwt.dev.DevMode.main(DevMode.java:429)
[WARNING] Google Web Toolkit 2.8.0
[WARNING] DevMode [-[no]startServer] [-port port-number | "auto"] [-logdir directory] [-logLevel (ERROR|WARN|INFO|TRACE|DEBUG|SPAM|ALL)] [-gen dir] [-bindAddress host-name-or-address] [-codeServerPort port-number | "auto"] [-[no]superDevMode] [-server servletContainerLauncher[:args]] [-startupUrl url] [-war dir] [-deploy dir] [-extra dir] [-modulePathPrefix ] [-workDir dir] [-XmethodNameDisplayMode (NONE|ONLY_METHOD_NAME|ABBREVIATED|FULL)] [-sourceLevel [auto, 1.8]] [-[no]generateJsInteropExports] [-[no]incremental] [-style (DETAILED|OBFUSCATED|PRETTY)] [-[no]failOnError] [-setProperty name=value,value...] module[s] 
[WARNING] 

```

The EmbeddedWildFlyLauncher class is in the errai-cdi-jboss jar.

In rc6 and rc7, we had to add it to the `gwt-app` normal dependencies, which is a hack because technically the client doesn't need it:

```
  <artifactId>optashift-employee-rostering-gwtui</artifactId>
  <packaging>gwt-app</packaging>
  ...
  <dependencies>
    <dependency>
      <!-- HACK WORKS IN RC6 AND RC7 - Only used for EmbeddedWildFlyLauncher during GWT Super Dev Mode -->
      <groupId>org.jboss.errai</groupId>
      <artifactId>errai-cdi-jboss</artifactId>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
```

That doesn't work on rc8 any more. However, the good way, adding an extra dependency on the plugin itself, still doesn't work either:

```
        <plugin>
          <groupId>net.ltgt.gwt.maven</groupId>
          <artifactId>gwt-maven-plugin</artifactId>
          <version>1.0-rc-8</version>
          ...
          <dependencies>
            <dependency> <!-- DOES NOT WORK IN RC6, RC7 AND RC8 -->
              <groupId>org.jboss.errai</groupId>
              <artifactId>errai-cdi-jboss</artifactId>
              <version>${version.org.jboss.errai}</version>
            </dependency>
          </dependencies>
        </plugin>
```

To reproduce: `git clone https://github.com/kiegroup/optashift-employee-rostering && cd optashift-employee-rostering && mvn gwt:devmode`

**Comment by ge0ffrey** [comment]
@mbarkley fyi

**Comment by tbroyer** [comment]
> In rc6 and rc7, we had to add it to the `gwt-app` normal dependencies, which is a hack because technically the client doesn't need it

Using `<scope>runtime</scope>` is **not** a hack, it's how this plugin has been designed: https://tbroyer.github.io/gwt-maven-plugin/codeserver.html

> However, the good way, adding an extra dependency on the plugin itself, still doesn't work either

How would adding dependencies to the plugin classloader be "the good way", knowing that it forks a JVM to explicitly avoid polluting the classpath with Maven dependencies? (among other, more important things)  
Defining extra dependencies to be added to the DevMode classpath would be possible (and _that_ could be called "the good way", similar to the `<annotationProcessorPaths>` from the maven-compiler-plugin), but actually GWT is trying to move away from DevMode, so I'm reluctant to do it.

---

That being said, you're right there's a regression in rc-8 regarding runtime dependencies.

**Comment by ge0ffrey** [comment]
@tbroyer I completely agree with your second paragraph. Adding it as a plugin dependency is indeed even more wrong.

As for the first one, I partially agree. Note that `errai-cdi-jboss.jar` is special, in the sense that's is a dependency for SDM, not the GWT compilation. It's the jar that contains the -server extension to launch WildFly in the backend, it's not used by the client side code normally. The production (non-SDM) build should not have it in any classpath, but it currently does have it. As such, I don't think it belongs in the gwt-app classpath (as it pollutes it). I don't mind it being there, but I do think it's a gentle hack.

Side note: I have a hard time understanding the text in codeserver.html (I'd rather see code example instructions than sentence instructions), but I love the architecture (classpath splitting client/server, packaing types, etc). Might just be me.

**Comment by tbroyer** [comment]
> The production (non-SDM) build should not have it in any classpath, but it currently does have it.

No it doesn't (or at least shouldn't). Because `gwt:compile` only uses dependencies with scope `compile` (or `provided` or `system`; the same that are used in the compile classpath by the maven-compiler-plugin when compiling the classes with JavaC), dependencies with scope `runtime` will only be added to the classpath for DevMode; and actually also present in the _test_ classpath, when compiling your `src/test/java` and running your test (so, yes, adding a `<devmodeExtraDependencies>` might be a good idea, but as I said, GWT is moving away from the embedded server / all-in-one devmode with-mixed-client-and-server-classpaths, so I'd rather live with that wart in the test classpath than add support for something we don't want people to actually use).  
(notice once again how Maven's design is broken, with the test classpath merging all scopes –including `provided` and `runtime`– and using them both for compiling and running the test)

Notice also how I explicitly discourage the use of `gwt:devmode` in codeserver.html in favor of `gwt:codeserver`; and discourage its use even more for running webapps (which is what you want to do here, additionally with a custom servlet container launcher)

---
> Side note: I have a hard time understanding the text in codeserver.html (I'd rather see code example instructions than sentence instructions), but I love the architecture (classpath splitting client/server, packaing types, etc). Might just be me.

It indeed uses some _advanced_ Maven terminology; the idea being that if you don't know what those things are, I'm expecting that you won't actually need them, and/or you should search for their meaning (what does “reactor” means in the context of Maven? what's an “aggregator goal”? what about the “`process-classes` phase“? or the `-pl` and `-am` arguments?) It also doesn't explain what GWT's CodeServer does or does not do, as it expects some prior knowledge of GWT's architecture and tooling.  
This is documentation for the plugin, not a tutorial for either/both GWT and/or Maven. I understand that's why some people would like to find, but I don't have the resources to write and maintain such documentation. This is also why I'm providing archetypes (linked from that doc).

So, I conceed this is not really "user friendly" documentation, and I'm open to suggestions to improve it; but I likely won't ever write any tutorial-like documentation.

**Comment by ge0ffrey** [comment]
Agreed with first paragraph.
Second paragraph: The reason we're using `gwt:devmode` is because I tried a dozen ways to get `gwt:codeserver` etc to work with the WildFly backend, but I could not get it to work. If there is a way, it should be documented because it's not straightforward. I am happy to try any additional suggestions and document it if I get it to work. My code is here: https://github.com/kiegroup/optashift-employee-rostering/blob/master/pom.xml#L204 - it's easy to reproduce locally (git clone && mvn clean install && mvn gwt:devmode).

**Comment by tbroyer** [comment]
> The reason we're using `gwt:devmode` is because I tried a dozen ways to get `gwt:codeserver` etc to work with the WildFly backend, but I could not get it to work.

I don't know WildFly so can't really comment, but the requirements are: be able to deploy from an "exploded war" and/or (ideally) overlay a directory of web resources on top of the war. This is how I do it with Jetty and Tomcat in my archetypes, with a specific directory as `launcherDir` that's overlayed on top of the webapp.
If overlaying is impossible (e.g. AppEngine), then having the server serve the webapp directly from the "exploded war" directory is a must; you then configure that directory as the `launcherDir` and need to make sure you `mvn clean` before you package your webapp for deployment (or you'll deploy the SDM stub nocache.js instead of the production one).
As a last resort, you could try https://github.com/tbroyer/gwt-devserver.

Other developers using WildFly probably already have similar needs when dealing with other front-end tools (e.g. `gulp watch` or similar that watch and rebuilds their SASS stylesheets or Babel/Rollup scripts).

I agree this needs to be properly documented, but on gwtproject.org directly.

Let's continue this discussion on the GWT Forum if you don't mind, as this goes beyond this plugin or even just using Maven. Unless you find the answer in the WildFly community (feel free to share it somewhere: GWT Forum, GWT G+ Community, etc. so others can benefit.)

> Try my 5 puzzlers :)

OMG question 5! wtaf!

> The thing that confuses me in that codeserver doc is DevMode vs SuperDevMode in combination with vanilla backend vs a custom backend.
> The combination of SuperDevMode and a custom backend eludes me.

Now I have a hard time parsing what you're saying here :)

`gwt:codeserver` is GWT's CodeServer. Needs some web server to serve your HTML host page and stub nocache.js. See requirements above (they assume a WAR-packaged webapp though, whereas `gwt:codeserver` makes no single assumption about the backend).
`gwt:devmode` is GWT's DevMode. I personally don't recommend using it other than to serve static files, because of some issues with the classloader (which you possibly don't have with the custom WildFly servler container launcher). I'd go as far as to even recommend only ever possibly setting up a reverse-proxy servlet in the "webapp" to proxy requests to your real backend; that'd be very similar to gwt-devserver then. This setup I could possibly see documented on codeserver.html.

Let's continue the discussion in another issue (or your PR for codeserver.html) or the GWT Forum though.

**Comment by tbroyer** [comment]
I think the regression has been introduced by d45999f3c3d053fc66435455817931c32899bf31, where the executed projects don't have their runtime dependencies resolved / available in `.getArtifacts()` when computing the classpath.

I'd appreciate if you have the opportunity to test a build with this commit reverted, as I probably won't have time to get my hands on my dev env before a few days (where few could mean up to 10 days).

**Comment by tbroyer** [comment]
I reverted the offending commit a couple weeks ago, and fixed the Travis build yesterday so snapshots are published again; would you mind testing with the latest snapshot?

**Comment by ge0ffrey** [comment]
We recently switched to gwt:codeserver (thanks to @Christopher-Chianelli changes), but I 'll grab a historic revision with devmode to verify it for you.
Thanks, Thomas!
